# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_cat',
            field=models.CharField(blank=True, choices=[('pe1or3', '体育1或3'), ('pe2or4', '体育2或4')], max_length=20, null=True, verbose_name='上课类别'),
        ),
    ]
