# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='add_number',
            field=models.IntegerField(default=0, verbose_name='排课新增人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_cat',
            field=models.CharField(choices=[('pe1or2', '专项1或2'), ('pe3or4', '专项3或4')], max_length=20, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_cat',
            field=models.CharField(blank=True, choices=[('pe1or2', '专项1或2'), ('pe3or4', '专项3或4')], default='', max_length=20, verbose_name='上课类别'),
        ),
    ]
