# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 04:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170812_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(help_text='身份证号后8位', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9]{7}[a-z,A-X]{1}$|^[0-9]{8}$', '身份证号后8位', 'invalid')], verbose_name='身份证号后8位'),
        ),
    ]
