# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '导入导出与自动排课',
                'verbose_name_plural': '导入导出与自动排课',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_cat', models.CharField(choices=[('1', '春季'), ('2', '秋季')], default='1', max_length=10, verbose_name='学期')),
                ('min_select_count', models.IntegerField(default=3, verbose_name='至少选择可上课节数')),
                ('online_flag', models.BooleanField(default=True, verbose_name='系统上线')),
                ('notification', models.TextField(blank=True, default='', max_length=300, verbose_name='登录提醒')),
                ('fail_msg', models.TextField(blank=True, default='', max_length=200, verbose_name='到办公室登记说明')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
