# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 03:04
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SiteSetting = apps.get_model("ioadmin", "SiteSetting")
    db_alias = schema_editor.connection.alias
    SiteSetting.objects.using(db_alias).bulk_create([
        SiteSetting(),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '导入导出与自动排课',
                'verbose_name_plural': '导入导出与自动排课',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_flag', models.BooleanField(default=True, verbose_name='系统上线')),
                ('notification', models.TextField(blank=True, default='', max_length=300, verbose_name='登录提醒')),
                ('fail_msg', models.TextField(blank=True, default='', max_length=200, verbose_name='到办公室登记说明')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.RunPython(forwards_func),
    ]
