# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='course_cat',
            field=models.CharField(choices=[('1', '春季'), ('2', '秋季')], default='1', max_length=10, verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='min_select_count',
            field=models.IntegerField(default=3),
        ),
    ]
